version: '3.1'

services:
  db:
    image: mariadb
    restart: "no"
    container_name: sea-adventures-database
    environment:
      MARIADB_USER: MARIADB_USER
      MARIADB_PASSWORD: MARIADB_PASSWORD
      MARIADB_DATABASE: MARIADB_DATABASE
      MARIADB_ROOT_PASSWORD: MARIADB_ROOT_PASSWORD
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    volumes:
      - sea-adventures-database-data:/etc/mysql/conf.d
      - ./password.cnf:/password.cnf
    ports:
      - "3306:3306"
volumes:
  sea-adventures-database-data:
