version: '3.1'

services:
  db:
    image: mariadb
    restart: "no"
    container_name: mariadb
    environment:
      MARIADB_USER: eric
      MARIADB_PASSWORD: eric1234
      MARIADB_DATABASE: eric-db
      MARIADB_ROOT_PASSWORD: ericroot1234
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mariadb-data:/etc/mysql/conf.d
      - ./password.cnf:/password.cnf
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    container_name: adminer
    restart: "no"
    ports:
      - "8080:8080"
volumes:
  mariadb-data:
